language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
matrix:
  fast_finish: true
  # WWTD doesn't support allow_failures... yet
  # allow_failures:
  #   - rvm: ruby-head
gemfile:
  - spec/gemfiles/40.gemfile
  - spec/gemfiles/41.gemfile
  - spec/gemfiles/42.gemfile
script: bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: never
