language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
matrix:
  fast_finish: true
  # WWTD doesn't support allow_failures... yet
  # allow_failures:
  #   - rvm: ruby-head
gemfile:
  - spec/gemfiles/52.gemfile
  - spec/gemfiles/60.gemfile
  - spec/gemfiles/61.gemfile
script: bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: never
